import type { Script } from '$lib/types/Script';
import { settingsStore } from '$lib/utils/stores/store';
import { getCharacterName, type Language } from '$lib/utils/translations';
import { getScriptTranslationWithFallback } from '$lib/utils/getScriptTranslation';

let currentLanguage: Language = 'en';
settingsStore.subscribe((value) => {
	currentLanguage = (value.language as Language) || 'en';
});

const script: Script = {
	lines: [
		{
			id: 1,
			speakers: [getCharacterName(currentLanguage, 'botBuddy')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 1),
			avatars: ['/img/characters/bot-buddy/bot-buddy-warning.png'],
			background: '/img/backgrounds/level1/2.png',
			audio: '/audio/level2/bot_buddy/Botbuddy_l2s1.wav',
			pos: 'center',
            size: 'full',
		},
        {
            id: 2,
            speakers: [getCharacterName(currentLanguage, 'computerVoice')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 2),
            avatars: ['/img/characters/bot-buddy/bot-buddy-warning.png'],
            background: '/img/backgrounds/level1/2.png',
			audio: '/audio/level1/bot_buddy/bot_buddy_l1s45.wav',
            pos: 'left'
        },
        {
            id: 3,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 3),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level1/2.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s3.wav',
            pos: 'left'
        },
        {
            id: 4,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 4),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school2.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s4.wav',
            pos: 'left'
        },
        {
            id: 5,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 5),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school3.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s5.wav',
            pos: 'left'
        },
        {
            id: 6,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 6),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school4.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s6.wav',
            pos: 'left'
        },
        {
            id: 7,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 7),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school5.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s7.wav',
            pos: 'left'
        },
        {
            id: 8,
            speakers: ['', getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 8),
            avatars: ['/img/characters/level-2/boy/boy_sad_flipped-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s8.wav',
            pos: 'right'
        },
        {
            id: 9,
            speakers: [getCharacterName(currentLanguage, 'kelvin'), ''],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 9),
            avatars: ['/img/characters/level-2/boy/boy_fist-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s9.wav',
            pos: 'right'
        },
        {
            id: 10,
            speakers: [getCharacterName(currentLanguage, 'kelvin'), ''],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 10),
            avatars: [ '/img/characters/level-2/boy/boy_frustrated_flipped-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s10.wav',
            pos: 'left'
        },
        {
            id: 11,
            speakers: ['', getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 11),
            avatars: ['/img/characters/level-2/boy/boy_sad_flipped-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s11.wav',
            pos: 'left'
        },
        {
            id: 12,
            speakers: [getCharacterName(currentLanguage, 'kelvin'), ''],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 12),
            avatars: ['/img/characters/level-2/boy/boy_hmm_flipped-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s12.wav',
            pos: 'right'
        },
        {
            id: 13,
            speakers: ['', getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 13),
            avatars: ['/img/characters/level-2/boy/boy_huh.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s13.wav',
            pos: 'left'
        },
        {
            id: 14,
            speakers: ['', getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 14),
            avatars: ['/img/characters/level-2/boy/boy_huh.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s14.wav',
            pos: 'left'
        },
        {
            id: 15,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 15),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s15.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 16,
            speakers: ['', getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 16),
            avatars: ['', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s16.wav',
            pos: 'left'
        },
        {
            id: 17,
            speakers: [getCharacterName(currentLanguage, 'computerVoice')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 17),
            avatars: [''],
            background: '/img/backgrounds/level2/car.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s17.wav',
            pos: 'left'
        },
        {
            id: 18,
            speakers: [getCharacterName(currentLanguage, 'computerVoice')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 18),
            avatars: [''],
            background: '/img/backgrounds/level2/car.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s18.wav',
            pos: 'left'
        },
        {
            id: 19,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 19),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s19.wav',
            pos: 'left'
        },
        {
            id: 20,
            speakers: [getCharacterName(currentLanguage, 'computerVoice')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 20),
            avatars: [''],
            background: '/img/backgrounds/level2/car.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s17.wav',
            pos: 'left'
        },
        {
            id: 21,
            speakers: [getCharacterName(currentLanguage, 'computerVoice')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 21),
            avatars: [''],
            background: '/img/backgrounds/level2/car.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s18.wav',
            pos: 'left'
        },
        {
            id: 22,
            speakers: [getCharacterName(currentLanguage, 'kelvin')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 22),
            avatars: ['/img/characters/level-2/boy/boy_huh.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s22.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 23,
            speakers: [getCharacterName(currentLanguage, 'kelvin')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 23),
            avatars: [ '/img/characters/level-2/boy/boy_frustrated_flipped-removebg-preview.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s23.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 24,
            speakers: ['', getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 24),
            avatars: ['/img/characters/level-2/boy/boy_hmm_flipped-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s24.wav',
            pos: 'left'
        },
        {
            id: 25,
            speakers: [getCharacterName(currentLanguage, 'kelvin'), ''],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 25),
            avatars: ['/img/characters/level-2/boy/boy_talking_2-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png',],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s25.wav',
            pos: 'right'
        },
        {
            id: 26,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 26),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s26.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 27,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 27),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s27.wav',
            pos: 'center',
        },
        {
            id: 28,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 28),
            avatars: [''],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s28.mp3',
            pos: 'center',
        },
        {
            id: 29,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 29),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level1/bot_buddy/bot_buddy_l2s29.wav',
            pos: 'center',
        },
        {
            id: 30,
            speakers: [getCharacterName(currentLanguage, 'museumOfRobotHistory')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 30),
            avatars: ['/img/misc/map-icons/museumavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s30.wav',
            pos: 'center',
        },
        {
            id: 31,
            speakers: [getCharacterName(currentLanguage, 'pizzaPlace')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 31),
            avatars: ['/img/misc/map-icons/pizzaplaceavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s31.wav',
            pos: 'center',
        },
        {
            id: 32,
            speakers: [getCharacterName(currentLanguage, 'iceCreamPalace')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 32),
            avatars: ['/img/misc/map-icons/icecreamavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s32.wav',
            pos: 'center',
        },
        {
            id: 33,
            speakers: [getCharacterName(currentLanguage, 'fireStation')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 33),
            avatars: ['/img/misc/map-icons/firestationavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s33.wav',
            pos: 'center',
        },
        {
            id: 34,
            speakers: [getCharacterName(currentLanguage, 'worldsLargestToilet')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 34),
            avatars: ['/img/misc/map-icons/toiletavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s34.wav',
            pos: 'center',
        },
        {
            id: 35,
            speakers: [getCharacterName(currentLanguage, 'vroomVroomCarFactory')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 35),
            avatars: ['/img/misc/map-icons/vroomavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s35.wav',
            pos: 'center',
        },
        {
            id: 36,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 36),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/elevators.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s36.wav',
            pos: 'left',
        },
        {
            id: 37,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 37),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s37.wav',
            pos: 'left',
        },
        {
            id: 38,
            speakers: [getCharacterName(currentLanguage, 'botBuddy'), ''],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 38),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png', '/img/misc/icecreamscream.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/l2s38.ogg',
            pos: 'left',
        },
        {
            id: 39,
            speakers: ['', getCharacterName(currentLanguage, 'stEel')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 39),
            avatars: [ '/img/characters/bot-buddy/bot-buddy-happy.png', '/img/characters/level-2/steel/steel_wave.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/steel/Steel_l2s39.wav',
            pos: 'right',
        },
        {
            id: 40,
            speakers: ['', getCharacterName(currentLanguage, 'stEel')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 40),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png', '/img/characters/level-2/steel/steel_thumb.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/steel/Steel_l2s40.wav',
            pos: 'right',
        },
        {
            id: 41,
            speakers: [getCharacterName(currentLanguage, 'botBuddy'), ''],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 41),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png', '/img/characters/level-2/steel/steel_stand.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s41.wav',
            pos: 'left',
        },
        {
            id: 42,
            speakers: ['', getCharacterName(currentLanguage, 'stEel')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 42),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png', '/img/characters/level-2/steel/steel_hands.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/steel/Steel_l2s42.wav',
            pos: 'right',
        },
        {
            id: 43,
            speakers: ['', getCharacterName(currentLanguage, 'stEel')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 43),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png', '/img/characters/level-2/steel/steel_thumb.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/steel/Steel_l2s43.wav',
            pos: 'right',
        },
        {
            id: 44,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 44),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s44.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 45,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 45),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/factory1.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s45.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 46,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 46),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s46.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 47,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level2', 'main', 47),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s47.wav',
        }
	],
};

export default script;