import type { Script } from '$lib/types/Script';

const script: Script = {
	lines: [
		{
			id: 1,
			speakers: ['Bot Buddy'],
			dialog:
				'Oh! It looks like we are getting an alert! Let’s see what it says!',
			avatars: ['/img/characters/bot-buddy/bot-buddy-warning.png'],
			background: '/img/backgrounds/level1/2.png',
			audio: '/audio/level2/bot_buddy/Botbuddy_l2s1.wav',
			pos: 'center',
            size: 'full',
		},
        {
            id: 2,
            speakers: ['Computer Voice'],
            dialog:
                'BEEP BEEP Detecting problems with technology ahead! Detecting problems with technology ahead!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-warning.png'],
            background: '/img/backgrounds/level1/2.png',
			audio: '/audio/level1/bot_buddy/bot_buddy_l1s45.wav',
            pos: 'left'
        },
        {
            id: 3,
            speakers: ['Bot Buddy'],
            dialog:
                'Let’s go see if we can find one of those cars and investigate what the problem is!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level1/2.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s3.wav',
            pos: 'left'
        },
        {
            id: 4,
            speakers: ['Bot Buddy'],
            dialog: 'We found one! Oh, there are no drivers needed! How do these cars work?',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school2.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s4.wav',
            pos: 'left'
        },
        {
            id: 5,
            speakers: ['Bot Buddy'],
            dialog: 'Amazing! In the future, they use cameras to scan people\'s faces and that allows them to get a ride.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school3.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s5.wav',
            pos: 'left'
        },
        {
            id: 6,
            speakers: ['Bot Buddy'],
            dialog: 'It seems like kids use these self-driving cars to get to school! So cool!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school4.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s6.wav',
            pos: 'left'
        },
        {
            id: 7,
            speakers: ['Bot Buddy'],
            dialog: 'Oh no, the self-driving car isn\'t working for that kid.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school5.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s7.wav',
            pos: 'left'
        },
        {
            id: 8,
            speakers: ['', 'Bot Buddy'],
            dialog: 'Hello, I am Bot Buddy. What\'s your name? Why isn\'t the car working for you?',
            avatars: ['/img/characters/level-2/boy/boy_sad_flipped-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s8.wav',
            pos: 'right'
        },
        {
            id: 9,
            speakers: ['Kelvin', ''],
            dialog: 'Hi, I\'m Kelvin. These self-driving cars never work for me except when I\'m with my parents. It\'s so frustrating! It only works for some of my friends.',
            avatars: ['/img/characters/level-2/boy/boy_fist-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s9.wav',
            pos: 'right'
        },
        {
            id: 10,
            speakers: ['Kelvin', ''],
            dialog: 'Today I have soccer practice, and I\'m going to be late…AGAIN!',
            avatars: [ '/img/characters/level-2/boy/boy_frustrated_flipped-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s10.wav',
            pos: 'left'
        },
        {
            id: 11,
            speakers: ['', 'Bot Buddy'],
            dialog: 'Don\'t worry! The SPOT team is here to help!',
            avatars: ['/img/characters/level-2/boy/boy_sad_flipped-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s11.wav',
            pos: 'left'
        },
        {
            id: 12,
            speakers: ['Kelvin', ''],
            dialog: 'Umm, the what?',
            avatars: ['/img/characters/level-2/boy/boy_hmm_flipped-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s12.wav',
            pos: 'right'
        },
        {
            id: 13,
            speakers: ['', 'Bot Buddy'],
            dialog: 'The... the.. Serving People on Transportation Team!',
            avatars: ['/img/characters/level-2/boy/boy_huh.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s13.wav',
            pos: 'left'
        },
        {
            id: 14,
            speakers: ['', 'Bot Buddy'],
            dialog: 'Yes, that is definitely who we work for! We are not secret agents or anything like that...',
            avatars: ['/img/characters/level-2/boy/boy_huh.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s14.wav',
            pos: 'left'
        },
        {
            id: 15,
            speakers: ['Bot Buddy'],
            dialog: 'Sorry, Agent. I almost blew our cover again!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s15.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 16,
            speakers: ['', 'Bot Buddy'],
            dialog: 'Let\'s test the self-driving car. Agent, could you try to scan your face and see if this car works for you?',
            avatars: ['', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school6.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s16.wav',
            pos: 'left'
        },
        {
            id: 17,
            speakers: ['Computer Voice'],
            dialog: 'Hold your face still for a scan...',
            avatars: [''],
            background: '/img/backgrounds/level2/car.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s17.wav',
            pos: 'left'
        },
        {
            id: 18,
            speakers: ['Computer Voice'],
            dialog: 'Face Scan Failed.',
            avatars: [''],
            background: '/img/backgrounds/level2/car.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s18.wav',
            pos: 'left'
        },
        {
            id: 19,
            speakers: ['Bot Buddy'],
            dialog: 'Agent, it didn\'t work. Try it again. Maybe try smiling really big this time!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s19.wav',
            pos: 'left'
        },
        {
            id: 20,
            speakers: ['Computer Voice'],
            dialog: 'Hold your face still for a scan...',
            avatars: [''],
            background: '/img/backgrounds/level2/car.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s17.wav',
            pos: 'left'
        },
        {
            id: 21,
            speakers: ['Computer Voice'],
            dialog: 'Face Scan Failed.',
            avatars: [''],
            background: '/img/backgrounds/level2/car.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s18.wav',
            pos: 'left'
        },
        {
            id: 22,
            speakers: ['Kelvin'],
            dialog: 'What? It didn\'t work for you? I wonder why it doesn\'t work for some kids? We miss so many birthday parties and sometimes school!',
            avatars: ['/img/characters/level-2/boy/boy_huh.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s22.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 23,
            speakers: ['Kelvin'],
            dialog: 'It\'s so unfair and not cool! Do you think you could do anything to help?',
            avatars: [ '/img/characters/level-2/boy/boy_frustrated_flipped-removebg-preview.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s23.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 24,
            speakers: ['', 'Bot Buddy'],
            dialog: 'Yes, Agent- I mean my friend and I... will investigate this problem!',
            avatars: ['/img/characters/level-2/boy/boy_hmm_flipped-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s24.wav',
            pos: 'left'
        },
        {
            id: 25,
            speakers: ['Kelvin', ''],
            dialog: 'That would be awesome if you could help! I have to go back inside and get an adult to make the car work, so I don\'t miss soccer practice again.',
            avatars: ['/img/characters/level-2/boy/boy_talking_2-removebg-preview.png', '/img/characters/bot-buddy/bot-buddy-happy.png',],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/kelvin/Kelvin_l2s25.wav',
            pos: 'right'
        },
        {
            id: 26,
            speakers: ['Bot Buddy'],
            dialog: 'Agent, this is terrible! We need to find out who makes these self-driving cars and why some kids need adults to help them catch rides!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s26.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 27,
            speakers: ['Bot Buddy'],
            dialog: 'The license plate on the self-driving car reads it\'s made by Vroom-Vroom car factory. Let\'s use my GPS and head over there.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s27.wav',
            pos: 'center',
        },
        {
            id: 28,
            speakers: ['Bot Buddy'],
            dialog: 'Agent, tap on my belly screen to access the GPS.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s28.wav',
            pos: 'center',
        },
        {
            id: 29,
            speakers: ['Bot Buddy'],
            dialog: 'Click on the location you want to go to.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level1/bot_buddy/bot_buddy_l2s29.wav',
            pos: 'center',
        },
        {
            id: 30,
            speakers: ['Museum of Robot History'],
            dialog: 'We’re sorry, our robots are being oiled right now. Come back later!',
            avatars: ['/img/misc/map-icons/museumavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s30.wav',
            pos: 'center',
        },
        {
            id: 31,
            speakers: ['Pizza Place'],
            dialog: 'You just ate!! Come back later when you are hungry again.',
            avatars: ['/img/misc/map-icons/pizzaplaceavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s31.wav',
            pos: 'center',
        },
        {
            id: 32,
            speakers: ['Ice Scream Palace'],
            dialog: 'Come back later! Our screamers are resting their voices.',
            avatars: ['/img/misc/map-icons/icecreamavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s32.wav',
            pos: 'center',
        },
        {
            id: 33,
            speakers: ['Fire Station'],
            dialog: 'We are busy getting a cat out of a tree. Come back later!',
            avatars: ['/img/misc/map-icons/firestationavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s33.wav',
            pos: 'center',
        },
        {
            id: 34,
            speakers: ['World’s Largest Toilet'],
            dialog: 'We’ve got a clog on our hands! Come back later!',
            avatars: ['/img/misc/map-icons/toiletavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s34.wav',
            pos: 'center',
        },
        {
            id: 35,
            speakers: ['Vroom-Vroom Car Factory'],
            dialog: 'We’re open! Come on over!',
            avatars: ['/img/misc/map-icons/vroomavatar.png'],
            background: '/img/backgrounds/level2/school8.png',
            audio: '/audio/level2/computer_voice/Computervoice_l2s35.wav',
            pos: 'center',
        },
        {
            id: 36,
            speakers: ['Bot Buddy'],
            dialog: 'Looks like the visitor elevator for the Vroom-Vroom car factory is here. Agent, press on the visitor button.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/elevators.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s36.wav',
            pos: 'left',
        },
        {
            id: 37,
            speakers: ['Bot Buddy'],
            dialog: 'Here we are! Maybe someone can give us some information about the self-driving cars.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s37.wav',
            pos: 'left',
        },
        {
            id: 38,
            speakers: ['Bot Buddy', ''],
            dialog: 'Wait what is that sound? Uh, hi, are you okay?',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png', '/img/misc/icecreamscream.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/l2s38.ogg',
            pos: 'left',
        },
        {
            id: 39,
            speakers: ['', 'ST-EE-L'],
            dialog: 'OH! I’m sorry, I didn\'t realize we had a visitor.  I was practicing my ice cream scream. I am planning to visit the Ice Scream Palace later.',
            avatars: [ '/img/characters/bot-buddy/bot-buddy-happy.png', '/img/characters/level-2/steel/steel_wave.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/steel/Steel_l2s39.wav',
            pos: 'right',
        },
        {
            id: 40,
            speakers: ['', 'ST-EE-L'],
            dialog: 'I am ST-EE-L, pronounced STEEL! How may I help you?',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png', '/img/characters/level-2/steel/steel_thumb.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/steel/Steel_l2s40.wav',
            pos: 'right',
        },
        {
            id: 41,
            speakers: ['Bot Buddy', ''],
            dialog: 'Great to meet you, STEEL! We would like to learn about your self-driving cars and how they work.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png', '/img/characters/level-2/steel/steel_stand.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s41.wav',
            pos: 'left',
        },
        {
            id: 42,
            speakers: ['', 'ST-EE-L'],
            dialog: 'You’ll want to meet my friend DASH, the company’s virtual guide! Dash knows everything about our self-driving cars!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png', '/img/characters/level-2/steel/steel_hands.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/steel/Steel_l2s42.wav',
            pos: 'right',
        },
        {
            id: 43,
            speakers: ['', 'ST-EE-L'],
            dialog: 'I just need to share some quick files with you, and you’ll be good to go! Say hi to Dash for me!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png', '/img/characters/level-2/steel/steel_thumb.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/steel/Steel_l2s43.wav',
            pos: 'right',
        },
        {
            id: 44,
            speakers: ['Bot Buddy'],
            dialog: 'I am scanning the files and the system tells me the car’s face scanner lets someone into the car based on algorithms. The cars use algorithms, or instructions, just like the robots in the pizza place.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/showroom.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s44.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 45,
            speakers: ['Bot Buddy'],
            dialog: 'We need to look at the algorithm the company developed to train their cars. The algorithm might help us find out why some kids can\'t get into the self driving cars!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/factory1.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s45.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 46,
            speakers: ['Bot Buddy'],
            dialog: 'Agent, I have sent the car training system files to your SPOT tablet!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s46.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 47,
            speakers: ['Bot Buddy'],
            dialog: 'Let’s go to the car training system and see if we can find out what is going on!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/audio/level2/bot_buddy/Botbuddy_l2s47.wav',
        }
	],
};

export default script;