import type { Script } from '$lib/types/Script';
import { settingsStore } from '$lib/utils/stores/store';
import { getCharacterName, type Language } from '$lib/utils/translations';
import { getScriptTranslationWithFallback } from '$lib/utils/getScriptTranslation';

let currentLanguage: Language = 'en';
settingsStore.subscribe((value) => {
	currentLanguage = (value.language as Language) || 'en';
});

const script: Script = {
	lines: [
        {
            id: 1,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 1),
            avatars: ['/img/characters/bot-buddy/bot-buddy-stop.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S1.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 2,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 2),
            avatars: ['/img/characters/bot-buddy/bot-buddy-alarm.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S2.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 3,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 3),
            avatars: [''],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S3.mp3',
            pos: 'center',
        },
        {
            id: 4,
            speakers: [getCharacterName(currentLanguage, 'kelvin')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 4),
            avatars: ['/img/characters/level-2/boy/boy_talking-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/level3/kelvin/kelvin_L3_S4.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 5,
            speakers: [getCharacterName(currentLanguage, 'kelvin')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 5),
            avatars: ['/img/characters/level-2/boy/boy_talking-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/level3/kelvin/kelvin_L3_S5.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 6,
            speakers: [getCharacterName(currentLanguage, 'kelvin')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 6),
            avatars: ['/img/characters/level-2/boy/boy_talking-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/level3/kelvin/kelvin_L3_S6.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 7,
            speakers: [getCharacterName(currentLanguage, 'hyunJoo')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 7),
            avatars: ['/img/characters/level-3/hyun-joo/hyun-joo_talking_crop.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/level3/kids/hyun-joo_L3_S7.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 8,
            speakers: [getCharacterName(currentLanguage, 'thomas')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 8),
            avatars: ['/img/characters/level-3/thomas/thomas_annoyed.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/level3/kids/thomas_L3_S8.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 9,
            speakers: [getCharacterName(currentLanguage, 'raj')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 9),
            avatars: ['/img/characters/level-3/raj/raj_fail-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/level3/kids/raj_L3_S9.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 10,
            speakers: [getCharacterName(currentLanguage, 'genevive')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 10),
            avatars: ['/img/characters/level-3/genevive/genevive_mad-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/level3/kids/genevive_L3_S10.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 11,
            speakers: [getCharacterName(currentLanguage, 'darnell')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 11),
            avatars: ['/img/characters/level-3/darnell/darnell_explain-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/level3/kids/darnell_L3_S11.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 12,
            speakers: [getCharacterName(currentLanguage, 'kelvin')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 12),
            avatars: ['/img/characters/level-2/boy/boy_talking-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/level3/kelvin/kelvin_L3_S12.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 13,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 13),
            avatars: ['/img/characters/bot-buddy/bot-buddy-ohno.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S13.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 14,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 14),
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S14.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 15,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 15),
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S15.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 16,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 16),
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S16.mp3',
        },
        {
            id: 17,
            speakers: [getCharacterName(currentLanguage, 'computerVoice')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 17),
            avatars: [''],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/computer_voice/computer_L3_S17.mp3',
        },
        {
            id: 18,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 18),
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S18.mp3',
        },
        {
            id: 19,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 19),
            avatars: ['/img/characters/bot-buddy/bot-buddy-angry.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S19.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 20,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 20),
            avatars: ['/img/characters/bot-buddy/bot-buddy-jump.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S20.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 21,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 21),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy-2.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S21.mp3',
            pos: 'center',
            size: 'full',
        },
        {
            id: 22,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 22),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy-2.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S22.mp3',
            pos: 'center',
            size: 'full',
        },
        // {
        //     id: 25,
        //     speakers: ['Bot Buddy'],
        //     dialog: 'If BIAS in MACHINE LEARNING is based on people\'s opinions, then we need to find out WHO developed the machine learning ALGORITHM for these cars.',
        //     avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
        //     background: '/img/backgrounds/level2/factory2.png',
        //     audio: '/level3/bot_buddy/bot_buddy_L3_S25.mp3',
        // },
        {
            id: 23,
            speakers: [getCharacterName(currentLanguage, 'botBuddy')],
            dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level3', 'main', 23),
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/level3/bot_buddy/bot_buddy_L3_S24.mp3',
            pos: 'center',
            size: 'full',
        }
    ]
};

export default script;