import type { Script } from '$lib/types/Script';
import type { UserData } from '$lib/types/UserData';
import { userDataStore } from '$lib/utils/stores/store';

let agent: UserData = {
	name: {
		first: '',
		last: ''
	},
	age: 0,
	interests: [],
	avatarImg: '',
	agentName: '',
	email: '',
	password: '',
	progress: {
		level: 0,
		levelLabel: '',
		subLevel: 0,
		subLevelLabel: '',
		lastUpdated: undefined
	}
};

userDataStore.subscribe((value) => {
	agent = value as UserData;
});



const script: Script = {
	lines: [
        {
            id: 1,
            speakers: ['Bot Buddy'],
            dialog: 'Finding out how the smart cars are trained and tested was super fun! I love downloading new information!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-stop.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s1.wav',
            pos: 'center',
        },
        {
            id: 2,
            speakers: ['Bot Buddy'],
            dialog: 'Now that we have this information, we should try to figure out why kids are having problems getting into self-driving cars',
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s2.wav',
            pos: 'center',
        },
        {
            id: 3,
            speakers: ['Bot Buddy'],
            dialog: 'It looks like I’m getting a news alert! Let\'s see what it says!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-ohno.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s3.wav',
            pos: 'center',
        },
        {
            id: 4,
            speakers: ['Bot Buddy'],
            dialog: 'Isn\'t this that same kid, Kelvin, we met earlier in front of the school? Agent, push on my belly screen to activate the story.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-ohno.png'],
            background: '/img/backgrounds/level2/factory2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s4.wav',
            pos: 'center',
        },
        {
            id: 5,
            speakers: ['Kelvin'],
            dialog: 'Thank you all for coming out today! We kids are here to protest the problems we are having with the self-driving cars in our neighborhoods!',
            avatars: ['/img/characters/level-2/boy/boy_talking-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s5.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 6,
            speakers: ['Kelvin'],
            dialog: 'These cars aren\'t opening for us, and kids need to get to places too! Just like adults!',
            avatars: ['/img/characters/level-2/boy/boy_talking-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s5.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 7,
            speakers: ['Kelvin'],
            dialog: 'It\'s not just me! There are other kids that have had the same problems. Let\'s hear from them.!',
            avatars: ['/img/characters/level-2/boy/boy_talking-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s5.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 8,
            speakers: ['Hyun-Joo'],
            dialog: ' I was late to soccer practice three times this week because the cars could not scan my face! I don\'t want to be late! What can we do to fix this?',
            avatars: ['/img/characters/level-3/hyun-joo/hyun-joo_talking_crop.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s5.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 9,
            speakers: ['Thomas'],
            dialog: 'Kids don\'t just have problems with the scanners on these cars. I can\'t even fit in the seats in the car! I\'m too short to read the map on the dashboard!',
            avatars: ['/img/characters/level-3/thomas/thomas_annoyed.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s5.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 10,
            speakers: ['Raj'],
            dialog: 'I have the same problem. The scans don\'t work on my face. I need an adult to make them work. Why aren\'t the cars designed so kids can use them easily?',
            avatars: ['/img/characters/level-3/raj/raj_fail-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s5.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 11,
            speakers: ['Genevive'],
            dialog: 'My dad said this even happened to him when he was a kid! Why hasn\'t this been fixed? Kids need to get places and not be late!',
            avatars: ['/img/characters/level-3/genevive/genevive_mad-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s5.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 12,
            speakers: ['Darnell'],
            dialog: 'It\'s like this everywhere! When I get to the mall, the face scanners are too high up for me to reach',
            avatars: ['/img/characters/level-3/darnell/darnell_explain-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s5.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 13,
            speakers: ['Kelvin'],
            dialog: 'Yes!!! Exactly! When will kids be more included in the design of our technologies?',
            avatars: ['/img/characters/level-2/boy/boy_talking-removebg-preview.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s5.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 14,
            speakers: ['Bot Buddy'],
            dialog: 'Oh no! It looks like the car scanner problem is affecting even more kids than we thought!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-ohno.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s14.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 15,
            speakers: ['Bot Buddy'],
            dialog: 'The kids talked about parents having the same issues accessing and using the self-driving cars when they were young too. So, the problem has been going on for a while',
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s15.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 16,
            speakers: ['Bot Buddy'],
            dialog: 'If we want to figure out WHY these cars aren\'t letting kids in, we need to see how the people at VroomVroom trained their machines.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s16.wav',
        },
        {
            id: 17,
            speakers: ['Bot Buddy'],
            dialog: 'Like we saw before, for a machine like a self-driving car or a bot buddy like me to learn, a person needs to give us data and TRAIN us. Let’s go back to the self-driving car data set on your tablet.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s17.wav',
        },
        {
            id: 18,
            speakers: ['Bot Buddy'],
            dialog: 'Here is part of the TRAINING dataset used to train the algorithm that lets people get rides in the cars. Let\'s take some notes in your journal about this dataset.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s18.wav',
        },
        {
            id: 19,
            speakers: ['Computer Voice'],
            dialog: 'What groups of people are represented in the dataset? What groups of people are not represented in the dataset?',
            avatars: [''],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s19.wav',
        },
        {
            id: 20,
            speakers: ['Bot Buddy'],
            dialog: 'Did you notice there were more pictures of adults than kids? There are no faces of kids for the face scanner on the car to learn from!',   
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s20.wav',
        },
        {
            id: 21,
            speakers: ['Bot Buddy'],
            dialog: 'These self-driving cars are BIASED against kids. BIAS is based on human opinions, Like when your data show that you prefer one thing over another.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy-2.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s21.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 22,
            speakers: ['Bot Buddy'],
            dialog: 'Remember when we had different opinions when making our favorite pizzas?',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s22.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 23,
            speakers: ['Bot Buddy'],
            dialog: 'Data can be BIASED because one thing is not represented in the data as much as another thing. Like this data has a LOT of adults and just a few kids.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy-2.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s23.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 24,
            speakers: ['Bot Buddy'],
            dialog: 'The face scanners for the cars were trained with very few images of kids but lots of adults. So, the cars are not recognizing that they should open their doors to kids.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-happy-2.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s24.wav',
            pos: 'center',
            size: 'full',
        },
        {
            id: 25,
            speakers: ['Bot Buddy'],
            dialog: 'If BIAS in MACHINE LEARNING is based on people\'s opinions, then we need to find out WHO developed the machine learning ALGORITHM for these cars.',
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s25.wav',
        },
        {
            id: 26,
            speakers: ['Bot Buddy'],
            dialog: 'C\'mon Agent! Let\'s teach these self-driving cars to recognize kids\' faces!',
            avatars: ['/img/characters/bot-buddy/bot-buddy-point.png'],
            background: '/img/backgrounds/level3/2.png',
            audio: '/audio/bot-buddy/bot-buddy-l3s26.wav',
        }
    ]
};

export default script;