export let trainingSetImgs = [
    '/img/traininator datasets/training set 1/pexels-10761393.jpg',
    '/img/traininator datasets/training set 1/pexels-3936894.jpg',
    '/img/traininator datasets/training set 1/pexels-5940020.jpg',
    '/img/traininator datasets/training set 1/pexels-5940022.jpg',
    '/img/traininator datasets/training set 1/pexels-alena-darmel-7322232.jpg',
    '/img/traininator datasets/training set 1/pexels-alexandru-molnar-7597466.jpg',
    '/img/traininator datasets/training set 1/pexels-allan-franca-carmo-5333090.jpg',
    '/img/traininator datasets/training set 1/pexels-amina-filkins-5561138.jpg',
    '/img/traininator datasets/training set 1/pexels-amina-filkins-5561141.jpg',
    '/img/traininator datasets/training set 1/pexels-anastasia-shuraeva-5704405.jpg',
    '/img/traininator datasets/training set 1/pexels-anastasia-shuraeva-5704736.jpg',
    '/img/traininator datasets/training set 1/pexels-andrea-piacquadio-3781916.jpg',
    '/img/traininator datasets/training set 1/pexels-andrea-piacquadio-3831569.jpg',
    '/img/traininator datasets/training set 1/pexels-andrea-piacquadio-3868631.jpg',
    '/img/traininator datasets/training set 1/pexels-andrea-piacquadio-788567.jpg',
    '/img/traininator datasets/training set 1/pexels-anna-shvets-5067742.jpg',
    '/img/traininator datasets/training set 1/pexels-anna-shvets-5257317.jpg',
    '/img/traininator datasets/training set 1/pexels-anna-shvets-5257474.jpg',
    '/img/traininator datasets/training set 1/pexels-anna-shvets-5257477.jpg',
    '/img/traininator datasets/training set 1/pexels-anna-shvets-5257495.jpg',
    '/img/traininator datasets/training set 1/pexels-anna-shvets-5257499.jpg',
    '/img/traininator datasets/training set 1/pexels-anna-shvets-5257554.jpg',
    '/img/traininator datasets/training set 1/pexels-arthouse-studio-4571943.jpg',
    '/img/traininator datasets/training set 1/pexels-august-de-richelieu-7428149.jpg',
    '/img/traininator datasets/training set 1/pexels-barbara-olsen-7869697.jpg',
    '/img/traininator datasets/training set 1/pexels-bhavesh-jain-3559739.jpg',
    '/img/traininator datasets/training set 1/pexels-chevanon-photography-2421934.jpg',
    '/img/traininator datasets/training set 1/pexels-cottonbro-10057606.jpg',
    '/img/traininator datasets/training set 1/pexels-cottonbro-5961941.jpg',
    '/img/traininator datasets/training set 1/pexels-cottonbro-6292756.jpg',
    '/img/traininator datasets/training set 1/pexels-cottonbro-6293197.jpg',
    '/img/traininator datasets/training set 1/pexels-cottonbro-6690063.jpg',
    '/img/traininator datasets/training set 1/pexels-cottonbro-7609953.jpg',
    '/img/traininator datasets/training set 1/pexels-dayvison-de-oliveira-silva-6263047.jpg',
    '/img/traininator datasets/training set 1/pexels-douglas-santiago-2589409.jpg',
    '/img/traininator datasets/training set 1/pexels-engin-akyurt-2174606.jpg',
    '/img/traininator datasets/training set 1/pexels-estudio-polaroid-3116381.jpg',
    '/img/traininator datasets/training set 1/pexels-evelina-zhu-5737177.jpg',
    '/img/traininator datasets/training set 1/pexels-furkanfdemir-6206939.jpg',
    '/img/traininator datasets/training set 1/pexels-furkanfdemir-7124299.jpg',
    '/img/traininator datasets/training set 1/pexels-gabriel-santos-1843896.jpg',
    '/img/traininator datasets/training set 1/pexels-gary-barnes-6248659.jpg',
    '/img/traininator datasets/training set 1/pexels-george-milton-6953595.jpg',
    '/img/traininator datasets/training set 1/pexels-ghen-mar-4313354.jpg',
    '/img/traininator datasets/training set 1/pexels-griffin-wooldridge-5088236.jpg',
    '/img/traininator datasets/training set 1/pexels-himesh-mehta-2856346.jpg',
    '/img/traininator datasets/training set 1/pexels-hitesh-ghate-2601464.jpg',
    '/img/traininator datasets/training set 1/pexels-italo-melo-1786258.jpg',
    '/img/traininator datasets/training set 1/pexels-ivan-babydov-7787914.jpg',
    '/img/traininator datasets/training set 1/pexels-jaroslav-nymbursk-3862753.jpg',
    '/img/traininator datasets/training set 1/pexels-jonas-kakaroto-2850984.jpg',
    '/img/traininator datasets/training set 1/pexels-jonas-kakaroto-2850985.jpg',
    '/img/traininator datasets/training set 1/pexels-joshua-mcknight-1139245.jpg',
    '/img/traininator datasets/training set 1/pexels-juan-vargas-6398330.jpg',
    '/img/traininator datasets/training set 1/pexels-kaboompics-com-6110.jpg',
    '/img/traininator datasets/training set 1/pexels-kampus-production-6667685.jpg',
    '/img/traininator datasets/training set 1/pexels-kampus-production-6950704.jpg',
    '/img/traininator datasets/training set 1/pexels-kampus-production-8422670.jpg',
    '/img/traininator datasets/training set 1/pexels-ketut-subiyanto-4350178.jpg',
    '/img/traininator datasets/training set 1/pexels-kindel-media-8172610.jpg',
    '/img/traininator datasets/training set 1/pexels-laura-garcia-3271268.jpg',
    '/img/traininator datasets/training set 1/pexels-laura-tancredi-7065261.jpg',
    '/img/traininator datasets/training set 1/pexels-liza-summer-6383015.jpg',
    '/img/traininator datasets/training set 1/pexels-los-muertos-crew-10041269.jpg',
    '/img/traininator datasets/training set 1/pexels-lucas-pezeta-1878522.jpg',
    '/img/traininator datasets/training set 1/pexels-marcelo-chagas-6357429.jpg',
    '/img/traininator datasets/training set 1/pexels-marcus-aurelius-6787920.jpg',
    '/img/traininator datasets/training set 1/pexels-marcus-aurelius-6787936.jpg',
    '/img/traininator datasets/training set 1/pexels-marllon-cristhian-barbosa-3110392.jpg',
    '/img/traininator datasets/training set 1/pexels-mart-production-7328511.jpg',
    '/img/traininator datasets/training set 1/pexels-mart-production-7330712.jpg',
    '/img/traininator datasets/training set 1/pexels-mary-taylor-5896618.jpg',
    '/img/traininator datasets/training set 1/pexels-meruyert-gonullu-6888761.jpg',
    '/img/traininator datasets/training set 1/pexels-michelle-zallouaa-6816181.jpg',
    '/img/traininator datasets/training set 1/pexels-mikhail-nilov-8317673.jpg',
    '/img/traininator datasets/training set 1/pexels-moe-magners-5333749.jpg',
    '/img/traininator datasets/training set 1/pexels-moe-magners-5335305.jpg',
    '/img/traininator datasets/training set 1/pexels-moe-magners-5335306.jpg',
    '/img/traininator datasets/training set 1/pexels-monstera-5876516.jpg',
    '/img/traininator datasets/training set 1/pexels-monstera-6238083.jpg',
    '/img/traininator datasets/training set 1/pexels-monstera-6310890.jpg',
    '/img/traininator datasets/training set 1/pexels-monstera-6311127.jpg',
    '/img/traininator datasets/training set 1/pexels-monstera-6311661.jpg',
    '/img/traininator datasets/training set 1/pexels-namgel-sherpa-4490075.jpg',
    '/img/traininator datasets/training set 1/pexels-omar-ramadan-6577460.jpg',
    '/img/traininator datasets/training set 1/pexels-ono-kosuki-5648376.jpg',
    '/img/traininator datasets/training set 1/pexels-ono-kosuki-5999814.jpg',
    '/img/traininator datasets/training set 1/pexels-pnw-production-8980772.jpg',
    '/img/traininator datasets/training set 1/pexels-polina-tankilevitch-6927556.jpg',
    '/img/traininator datasets/training set 1/pexels-rene-asmussen-638196.jpg',
    '/img/traininator datasets/training set 1/pexels-rodnae-productions-7845361.jpg',
    '/img/traininator datasets/training set 1/pexels-shvets-production-7544674.jpg',
    '/img/traininator datasets/training set 1/pexels-shvets-production-7544926.jpg',
    '/img/traininator datasets/training set 1/pexels-shvets-production-7545335.jpg',
    '/img/traininator datasets/training set 1/pexels-skyler-ewing-4904586.jpg',
    '/img/traininator datasets/training set 1/pexels-skyler-ewing-5422380.jpg',
    '/img/traininator datasets/training set 1/pexels-skyler-ewing-5422381.jpg',
    '/img/traininator datasets/training set 1/pexels-sora-shimazaki-5673486.jpg',
    '/img/traininator datasets/training set 1/pexels-svh-4250875.jpg',
    '/img/traininator datasets/training set 1/pexels-tarzine-jackson-773371.jpg',
    '/img/traininator datasets/training set 1/pexels-team-maestroo-4150434.jpg',
    '/img/traininator datasets/training set 1/pexels-tehmasip-khan-9678499.jpg',
    '/img/traininator datasets/training set 1/pexels-teona-swift-6873954.jpg',
    '/img/traininator datasets/training set 1/pexels-teona-swift-6873993.jpg',
    '/img/traininator datasets/training set 1/pexels-teona-swift-6874030.jpg',
    '/img/traininator datasets/training set 1/pexels-tim-mossholder-3336057.jpg',
    '/img/traininator datasets/training set 1/pexels-tim-samuel-5835016.jpg',
    '/img/traininator datasets/training set 1/pexels-vincent-tan-6934326.jpg',
    '/img/traininator datasets/training set 1/pexels-yaroslav-shuraev-8087566.jpg',
];

export let trainingSet1NoFaceImgs = [
    '/img/traininator datasets/training set 1 no face/1000_F_209374794_3NJxCae4izy2jiQd26ADWjLd8qwQGQG9.jpg',
    '/img/traininator datasets/training set 1 no face/Gray squirrel (Terry W. Johnson).jpg',
    '/img/traininator datasets/training set 1 no face/Modern_British_LED_Traffic_Light.jpg',
    '/img/traininator datasets/training set 1 no face/alex-preusser-0Qchak3o2a4-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/alvan-nee-8g0D8ZfFXyA-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/arnaud-mariat-45Z6hW1dQMI-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/brendan-church-pKeF6Tt3c08-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/craftsman-exterior.jpg',
    '/img/traininator datasets/training set 1 no face/daniel-gomez-CZS1R57uBEc-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/david-clode-AF0CrhiVCMM-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/ian-talmacs-1Xf8rhaLh5I-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/jk-sloan-co1wmDhPjKg-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/john-matychuk-dJdcb11aboQ-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/johnson-johnson-U6Q6zVDgmSs-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/modern house plan - carbondale__05776.original.jpg',
    '/img/traininator datasets/training set 1 no face/nathan-walker-Sv4btqhcYqw-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/niko-photos-tGTVxeOr_Rs-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/redd-francisco-sejLyCD2UQE-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/sardar-faizan-oZNe32A88O0-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/scott-webb-1ddol8rgUH8-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/tom-dils-_9zEZ7QBPiY-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/trnava-university-WGG4eD0rQmo-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/waldemar-tLj3fcfUgec-unsplash.jpg',
    '/img/traininator datasets/training set 1 no face/yosuke-ota-1JloC88VbQY-unsplash.jpg'
];

export let trainingSet2FaceImgs = [
    '/img/traininator datasets/training set 2/Picture1.jpg',
    '/img/traininator datasets/training set 2/Picture10.jpg',
    '/img/traininator datasets/training set 2/Picture11.jpg',
    '/img/traininator datasets/training set 2/Picture12.jpg',
    '/img/traininator datasets/training set 2/Picture13.jpg',
    '/img/traininator datasets/training set 2/Picture14.jpg',
    '/img/traininator datasets/training set 2/Picture15.jpg',
    '/img/traininator datasets/training set 2/Picture16.jpg',
    '/img/traininator datasets/training set 2/Picture17.jpg',
    '/img/traininator datasets/training set 2/Picture18.jpg',
    '/img/traininator datasets/training set 2/Picture19.jpg',
    '/img/traininator datasets/training set 2/Picture2.jpg',
    '/img/traininator datasets/training set 2/Picture20.jpg',
    '/img/traininator datasets/training set 2/Picture21.jpg',
    '/img/traininator datasets/training set 2/Picture22.jpg',
    '/img/traininator datasets/training set 2/Picture3.jpg',
    '/img/traininator datasets/training set 2/Picture4.jpg',
    '/img/traininator datasets/training set 2/Picture5.jpg',
    '/img/traininator datasets/training set 2/Picture6.jpg',
    '/img/traininator datasets/training set 2/Picture7.jpg',
    '/img/traininator datasets/training set 2/Picture8.jpg',
    '/img/traininator datasets/training set 2/Picture9.jpg',
];

export let testSet1Imgs = [
    '/img/traininator datasets/test set/pexels-2048716.jpg',
    '/img/traininator datasets/test set/pexels-7640389.jpg',
    '/img/traininator datasets/test set/pexels-allan-mas-5622395.jpg',
    '/img/traininator datasets/test set/pexels-amina-filkins-5560085.jpg',
    '/img/traininator datasets/test set/pexels-amina-filkins-5561138.jpg',
    '/img/traininator datasets/test set/pexels-barbara-olsen-7879739.jpg',
    '/img/traininator datasets/test set/pexels-cottonbro-7014762.jpg',
    '/img/traininator datasets/test set/pexels-eren-li-7169351.jpg',
    '/img/traininator datasets/test set/pexels-kamaji-ogino-5094100.jpg',
    '/img/traininator datasets/test set/pexels-kampus-production-6314558.jpg',
    '/img/traininator datasets/test set/pexels-karolina-grabowska-7296777.jpg',
    '/img/traininator datasets/test set/pexels-katerina-holmes-5905497.jpg',
    '/img/traininator datasets/test set/pexels-kelvin-octa-1096147.jpg',
    '/img/traininator datasets/test set/pexels-ketut-subiyanto-4473861.jpg',
    '/img/traininator datasets/test set/pexels-konstantin-mishchenko-6160380.jpg',
    '/img/traininator datasets/test set/pexels-mikhail-nilov-8923804.jpg',
    '/img/traininator datasets/test set/pexels-monstera-5063574.jpg',
    '/img/traininator datasets/test set/pexels-monstera-6186123.jpg',
    '/img/traininator datasets/test set/pexels-monstera-7139022.jpg',
    '/img/traininator datasets/test set/pexels-rodnae-productions-8385873.jpg',
    '/img/traininator datasets/test set/pexels-victoria-borodinova-1620760.jpg',
    '/img/traininator datasets/test set/bob-brewer-Y3U8HmtxTa8-unsplash.jpg',
    '/img/traininator datasets/test set/christoph-nolte-vfDnY63kY7E-unsplash.jpg',
    '/img/traininator datasets/test set/hari-nandakumar-hh9OkRFj-Pw-unsplash.jpg',
    '/img/traininator datasets/test set/logan-weaver-lgnwvr-T28_-7R7eek-unsplash.jpg',
    '/img/traininator datasets/test set/luca-ercolani-rMdhc3toUKk-unsplash.jpg',
    '/img/traininator datasets/test set/mathias-reding-QQzvJYuo_Q8-unsplash.jpg',
    '/img/traininator datasets/test set/michal-balog-33euGdt6YeQ-unsplash.jpg',
    '/img/traininator datasets/test set/samsung-memory-IJolVhJKk7c-unsplash.jpg',
    '/img/traininator datasets/test set/sichen-xiang-k2KPhZEZbBs-unsplash.jpg',
    '/img/traininator datasets/test set/silas-schneider-e9pUVc_yfNs-unsplash.jpg',
    '/img/traininator datasets/test set/alex-harwood-1SB-26irsMA-unsplash.jpg',
    '/img/traininator datasets/test set/casey-chae-3DrCZblTGoQ-unsplash.jpg',
    '/img/traininator datasets/test set/nasa-hubble-space-telescope-3jHQMBKWObM-unsplash.jpg',
    '/img/traininator datasets/test set/tegan-conway-CNuaf4gsYHA-unsplash.jpg',
];