
import type { Script } from '$lib/types/Script';

const script: Script = {
	lines: [
		{
			id: 1,
			speakers: ['Bot Buddy'],
			dialog: 'Now that our megajoules meter is full, its time to leave 2075 and go back to Mission Control! I bet the team has lots of questions for us!',
			avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
			background: '/img/backgrounds/level1/1.png',
			pos: 'left',
		},
		{
			id: 2,
			speakers: ['Bot Buddy'],
			dialog: 'Let’s go back to Mission Control!',
			avatars: [],
			background: '',
		},
		{
			id: 3,
			speakers: ['Captain Storm'],
			dialog: 'Welcome back,  Agent! We are excited to see you!',
			avatars: ['/img/characters/captain-storm/storm_yeah.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
		},
		{
			id: 4,
			speakers: ['Captain Storm'],
			dialog: 'You have shared so much with us in your travel log! We can’t wait to apply what you have learned to the design of our technology here!',
			avatars: ['/img/characters/captain-storm/storm_yeah.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
		},
		{
			id: 5,
			speakers: ['Captain Storm'],
			dialog: 'Now, we are going to talk about robots!',
			avatars: ['/img/characters/captain-storm/storm_yeah.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
		},
		{
			id: 6,
			speakers: ['Captain Storm'],
			dialog: 'Based on what you just learned in your time travel, you are going to help us design an AI robot prototype!',
			avatars: ['/img/characters/captain-storm/storm_yeah.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
		},
		{
			id: 7,
			speakers: ['Captain Storm'],
			dialog: 'Agent, on your SPOT tablet, open file named  “Robot Prototype.”',
			avatars: ['/img/characters/captain-storm/storm_yeah.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
		},
		{
			id: 8,
			speakers: ['SPOT Tablet'],
			dialog: 'SPOT TABLET WITH ROBOT PROTOTYPE BUTTON',
			avatars: [],
			background: '',
		},
		{
			id: 9,
			speakers: ['SPOT Tablet'],
			dialog: 'prototype menu',
			avatars: [],
			background: '',
		},
		{
			id: 10,
			speakers: ['SPOT Tablet'],
			dialog: 'design slide',
			avatars: [],
			background: '',
		},
		{
			id: 11,
			speakers: ['SPOT Computer'],
			dialog: 'For the future, I will design an AI robot with special abilities to help others. It will be able to ______',
			avatars: [],
			background: '',
		},
		{
			id: 12,
			speakers: ['SPOT Computer'],
			dialog: 'My robot would help the following people: _________',
			avatars: [],
			background: '',
		},
		{
			id: 13,
			speakers: ['SPOT Computer'],
			dialog: 'My robot is important and should be designed because  _______',
			avatars: [],
			background: '',
		},
		{
			id: 14,
			speakers: ['SPOT Computer'],
			dialog: 'When designing my robot, I will minimize bias by ___________',
			avatars: [],
			background: '',
		},
		{
			id: 15,
			speakers: ['SPOT Computer'],
			dialog: 'My robot will be named _________',
			avatars: [],
			background: '',
		},
		{
			id: 16,
			speakers: ['SPOT Computer'],
			dialog: 'Draw a picture of your robot',
			avatars: [],
			background: '',
		},
		{
			id: 17,
			speakers: ['SPOT Computer'],
			dialog: 'Robot Prototype design notes received!',
			avatars: [],
			background: '',
		},
		{
			id: 18,
			speakers: ['SPOT Computer'],
			dialog: 'COMBINED DESIGN NOTES',
			avatars: [],
			background: '',
		},
		{
			id: 19,
			speakers: ['SPOT Computer'],
			dialog: 'See [Teacher Agent] for CODE to proceed',
			avatars: [],
			background: '',
		},
		{
			id: 20,
			speakers: ['SPOT Computer'],
			dialog: 'It\'s time to decide on the data you will use to train your AI robot. Congratulations, your prototype idea has been approved!',
			avatars: [],
			background: '',
		},
		{
			id: 21,
			speakers: ['SPOT Tablet'],
			dialog: 'Prototype data menu',
			avatars: [],
			background: '',
		},
		{
			id: 22,
			speakers: ['SPOT Tablet'],
			dialog: 'Does this help to solve a problem in your community?',
			avatars: [],
			background: '',
		},
		{
			id: 23,
			speakers: ['SPOT Tablet'],
			dialog: 'It\'s time to decide on the data you will use to train your AI robot.  Give at least 6 examples of the images you will be using as training data for your robot.',
			avatars: [],
			background: '',
		},
		{
			id: 24,
			speakers: ['SPOT Tablet'],
			dialog: 'Take your training data examples and divide them up into classes or categories. Think about the “face” and “no face” classes you encountered during your travels.',
			avatars: [],
			background: '',
		},
		{
			id: 25,
			speakers: ['SPOT Tablet'],
			dialog: 'Name at least two classes for the training data examples you suggested.',
			avatars: [],
			background: '',
		},
		{
			id: 26,
			speakers: ['SPOT Tablet'],
			dialog: 'See [Teacher Agent] for SECRET CODE to proceed',
			avatars: [],
			background: '',
		},
		{
			id: 27,
			speakers: ['SPOT Tablet'],
			dialog: 'You may now proceed to TRAIN and TEST your AI robot. Congratulations, your training data classes have been approved!',
			avatars: [],
			background: '',
		},
		{
			id: 28,
			speakers: ['SPOT Tablet'],
			dialog: 'Prototype training menu',
			avatars: [],
			background: '',
		},
		{
			id: 29,
			speakers: ['SPOT Tablet'],
			dialog: 'You are about to enter the Traininator, where you will input data to train your robot to identify different classes.',
			avatars: [],
			background: '',
		},
		{
			id: 30,
			speakers: ['SPOT Tablet'],
			dialog: 'TRAININATOR',
			avatars: [],
			background: '',
		},
		{
			id: 31,
			speakers: ['SPOT Tablet'],
			dialog: 'You may now proceed to PROGRAM your AI robot. Congratulations, your Machine Learning Model is ready to use!',
			avatars: [],
			background: '',
		},
		{
			id: 32,
			speakers: ['SPOT Tablet'],
			dialog: 'Prototype programming menu',
			avatars: [],
			background: '',
		},
		{
			id: 33,
			speakers: ['SPOT Tablet'],
			dialog: 'You are about to enter the Codeinator, where you will create instructions for your AI robot to achieve its goal. First,  write your algorithm using an IF / THEN statement.',
			avatars: [],
			background: '',
		},
		{
			id: 34,
			speakers: ['SPOT Tablet'],
			dialog: 'CODEINATOR',
			avatars: [],
			background: '',
		},
    ],
};

export default script;