
import type { Script } from '$lib/types/Script';
import { settingsStore } from '$lib/utils/stores/store';
import { getCharacterName, type Language } from '$lib/utils/translations';
import { getScriptTranslationWithFallback } from '$lib/utils/getScriptTranslation';

let currentLanguage: Language = 'en';
settingsStore.subscribe((value) => {
	currentLanguage = (value.language as Language) || 'en';
});

const script: Script = {
	lines: [
		{
			id: 1,
			speakers: [getCharacterName(currentLanguage, 'botBuddy')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 1),
			avatars: ['/img/characters/bot-buddy/bot-buddy-happy.png'],
			background: '/img/backgrounds/level1/1.png',
			audio: '/audio/level4/bot_buddy/bot_buddy_l4s1.mp3',
			pos: 'left',
		},
		{
			id: 2,
			speakers: [getCharacterName(currentLanguage, 'botBuddy')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 2),
			avatars: [],
			background: '',
		},
		{
			id: 3,
			speakers: [getCharacterName(currentLanguage, 'captainStorm')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 3),
			avatars: ['/img/characters/captain-storm/storm_yeah.png', '/img/characters/agent-spark/spark_wave.png', '/img/characters/agent-fern/fern_thumbs_up.png', '/img/characters/agent-gear/vanil_cute.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
			audio: '/audio/level4/captain_storm/captain_storm_l4s3.mp3',
		},
		{
			id: 4,
			speakers: [getCharacterName(currentLanguage, 'captainStorm')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 4),
			avatars: ['/img/characters/captain-storm/storm_gesture_4_inverted.png', '/img/characters/agent-spark/spark_aww.png', '/img/characters/agent-fern/fern_sweet.png', '/img/characters/agent-gear/vanilla_gesture_2_inverted.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
			audio: '/audio/level4/captain_storm/captain_storm_l4s4.mp3',
		},
		{
			id: 5,
			speakers: [getCharacterName(currentLanguage, 'captainStorm')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 5),
			avatars: ['/img/characters/bot-buddy/bot-buddy-smug.png', '/img/characters/captain-storm/storm_gesture_4.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
			audio: '/audio/level4/captain_storm/captain_storm_l4s5.mp3',
		},
		{
			id: 6,
			speakers: [getCharacterName(currentLanguage, 'captainStorm')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 6),
			avatars: ['/img/characters/bot-buddy/bot-buddy-smug.png', '/img/characters/captain-storm/storm_gesture_4.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
			audio: '/audio/level4/captain_storm/captain_storm_l4s6.mp3',
		},
		{
			id: 7,
			speakers: [getCharacterName(currentLanguage, 'captainStorm')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 7),
			avatars: ['/img/characters/bot-buddy/bot-buddy-smug.png', '/img/characters/captain-storm/storm_gesture_4.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
			audio: '/audio/level4/captain_storm/captain_storm_l4s7.mp3',
		},
		{
			id: 8,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 8),
			avatars: [],
			background: '',
		},
		{
			id: 9,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 9),
			avatars: [],
			background: '',
		},
		{
			id: 10,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 10),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S12.mp3',
		},
		{
			id: 11,
			speakers: [getCharacterName(currentLanguage, 'spotComputer')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 11),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S13.mp3',
		},
		{
			id: 12,
			speakers: [getCharacterName(currentLanguage, 'spotComputer')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 12),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S14.mp3',
		},
		{
			id: 13,
			speakers: [getCharacterName(currentLanguage, 'spotComputer')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 13),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S16.mp3',
		},
		{
			id: 14,
			speakers: [getCharacterName(currentLanguage, 'spotComputer')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 14),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S17.mp3',
		},
		{
			id: 15,
			speakers: [getCharacterName(currentLanguage, 'captainStorm')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 15),
			avatars: ['/img/characters/bot-buddy/bot-buddy-smug.png', '/img/characters/captain-storm/storm_point.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
			audio: '/audio/level4/computer_voice/L4-S18.mp3',
		},
		{
			id: 16,
			speakers: [getCharacterName(currentLanguage, 'captainStorm')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 16),
			avatars: ['/img/characters/bot-buddy/bot-buddy-smug.png', '/img/characters/captain-storm/storm_point.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
			audio: '/audio/level4/computer_voice/L4-S19.mp3',
		},
		{
			id: 17,
			speakers: [getCharacterName(currentLanguage, 'spotComputer')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 17),
			avatars: [],
			background: '',
		},
		{
			id: 18,
			speakers: [getCharacterName(currentLanguage, 'spotComputer')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 18),
			avatars: [],
			background: '',
		},
		{
			id: 19,
			speakers: [getCharacterName(currentLanguage, 'spotComputer')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 19),
			avatars: [],
			background: '',
		},
		{
			id: 20,
			speakers: [getCharacterName(currentLanguage, 'spotComputer')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 20),
			avatars: [],
			background: '',
			audio: '',
		},
		{
			id: 21,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 21),
			avatars: [],
			background: '',
		},
		{
			id: 22,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 22),
			avatars: [],
			background: '',
		},
		{
			id: 23,
			dialog: '',
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			avatars: [],
			background: '',
		},
		{
			id: 24,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 24),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S27.mp3',
		},
		{
			id: 25,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 25),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S28.mp3',
		},
		{
			id: 26,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 26),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S29.mp3',
		},
		{
			id: 27,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 27),
			avatars: [],
			background: '',
		},
		{
			id: 28,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 28),
			avatars: [],
			background: '',
		},
		{
			id: 29,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 29),
			avatars: [],
			background: '',
		},
		{
			id: 30,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 30),
			avatars: [],
			background: '',
		},
		{
			id: 31,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 31),
			avatars: [],
			background: '',
		},
		{
			id: 32,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 32),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S34.mp3',
		},
		{
			id: 33,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 33),
			avatars: [],
			background: '',
		},
		{
			id: 34,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 34),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S36.mp3',
		},
		{
			id: 35,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 35),
			avatars: [],
			background: '',
		},
		{
			id: 36,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 36),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S38.mp3',
		},
		{
			id: 37,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 37),
			avatars: [],
			background: '',
		},
		{
			id: 38,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 38),
			avatars: [],
			background: '',
		},
		{
			id: 39,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 39),
			avatars: [],
			background: '',
		},
		{
			id: 40,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 40),
			avatars: [],
			background: '',
		},
		{
			id: 41,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 41),
			avatars: [],
			background: '',
		},
		{
			id: 42,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 42),
			avatars: [],
			background: '',
		},
		{
			id: 43,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 43),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S52.mp3',
		},
		{
			id: 44,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 44),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S54.mp3',
		},
		{
			id: 45,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 45),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S55.mp3',
		},
		{
			id: 46,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 46),
			avatars: [],
			background: '',
		},
		{
			id: 47,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 47),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S57.mp3',
		},
		{
			id: 48,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 48),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S58.mp3',
		},
		{
			id: 49,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 49),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S59.mp3',
		},
		{
			id: 50,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 50),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/L4-S60.mp3',
		},
		{
			id: 51,
			speakers: [getCharacterName(currentLanguage, 'captainStorm')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 51),
			avatars: ['/img/characters/captain-storm/storm_yeah.png'],
			background: '/img/backgrounds/Spark_Lab.jpg',
			audio: '/audio/level4/captain_storm/captain_storm_l4s61.mp3',
		},
		{
			id: 52,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 52),
			avatars: [],
			background: '',
			audio: '/audio/level4/computer_voice/52.mp3',
		},
		{
			id: 53,
			speakers: [getCharacterName(currentLanguage, 'spotTablet')],
			dialog: () => getScriptTranslationWithFallback(currentLanguage as any, 'level4new', 'main', 53),
			avatars: [],
			background: '',
		},
	],
};

export default script;